brew "git"
brew "neovim"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "fd"
brew "tree"
brew "stylua"
brew "tree-sitter-cli" # required by nvim-treesitter (main branch) to compile parsers

tap "hashicorp/tap"
brew "hashicorp/tap/vault"

brew "awscli"
brew "gh"
brew "node"
brew "python3"
brew "pipenv"
brew "uv"
brew "pyenv"
brew "direnv"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"
brew "starship"

cask "docker-desktop"
cask "zulu@17"
cask "zulu@11"
